DROP TABLE IF EXISTS "cities" CASCADE;
DROP TABLE IF EXISTS "app_userRoles" CASCADE;
DROP TABLE IF EXISTS "app_users" CASCADE;
DROP TABLE IF EXISTS "app_roles" CASCADE;

CREATE TABLE "cities"
(
	"id" BIGINT NOT NULL PRIMARY KEY,
	
	"name" VARCHAR(255) NOT NULL,
	
	"population" INT NOT NULL
);


CREATE TABLE "app_roles"
(
	"id" BIGINT NOT NULL PRIMARY KEY,
	
	"name" VARCHAR(255) NOT NULL,
	"desc" VARCHAR(255) NOT NULL
);


CREATE TABLE "app_users"
(
	"id" BIGINT NOT NULL PRIMARY KEY,
	
	"username" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL
);


CREATE TABLE "app_userRoles"
(
	"userID" BIGINT NOT NULL REFERENCES "app_users" ("id"),
	"roleID" BIGINT NOT NULL REFERENCES "app_roles" ("id")
);